/* 
 * Merchant API
 *
 * Afterpay Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using MerchantApi.Model;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing CaptureChargeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CaptureTests
    {
        // TODO uncomment below to declare an instance variable for CaptureChargeRequest
        private Capture instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CaptureChargeRequest
            instance = new Capture();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CaptureChargeRequest
        /// </summary>
        [Test]
        public void CaptureInstanceTest()
        {
            var amount = new Money("0.00", "NZD");
            instance = new Capture("1", "1", amount, "Capture for Order"); // Request Id needs to increas for each partial refund
            Assert.IsInstanceOf<Capture> (instance, "variable 'instance' is a Capture");
        }

    }

}
