/* 
 * Merchant API
 *
 * Afterpay Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using MerchantApi.Model;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing Checkout
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CheckoutTests
    {
        // TODO uncomment below to declare an instance variable for Checkout
        private Checkout instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Checkout
            instance = new Checkout();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Checkout
        /// </summary>
        [Test]
        public void CheckoutInstanceTest()
        {
            instance = new Checkout("001.8cutmcn24kftrlabog7sqi6hd57418l5s2t7a5okj7sq8j7p", "2021-01-17T12:40:50.468Z", "https://portal.sandbox.afterpay.com/nz/checkout/?token=001.8cutmcn24kftrlabog7sqi6hd57418l5s2t7a5okj7sq8j7p");
            Assert.IsInstanceOf<Checkout> (instance, "variable 'instance' is a Checkout");
        }

    }

}
