/* 
 * Merchant API
 *
 * Afterpay Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using MerchantApi.Model;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing Discount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DiscountTests
    {
        // TODO uncomment below to declare an instance variable for CaptureChargeRequest
        private Discount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {

        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CaptureChargeRequest
        /// </summary>
        [Test]
        public void DiscountTest()
        {
            var discountAmount = new Money("1.00", "NZD");

            instance = new Discount("Discount", discountAmount);
            Assert.IsInstanceOf<Discount> (instance, "variable 'instance' is a Discount");
        }

    }

}
