/* 
 * Merchant API
 *
 * Afterpay Merchant API Initial build
 *
 * OpenAPI spec version: 2017-03-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using MerchantApi.Model;

namespace MerchantApi.Test
{
    /// <summary>
    ///  Class for testing ErrorResponseErrorDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ErrorResponseErrorDetailsTests
    {
        // TODO uncomment below to declare an instance variable for ErrorResponseErrorDetails
        private ErrorResponseErrorDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ErrorResponseErrorDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorResponseErrorDetails
        /// </summary>
        [Test]
        public void ErrorResponseErrorDetailsInstanceTest()
        {
            Assert.IsInstanceOf<ErrorResponseErrorDetails> (instance, "variable 'instance' is a ErrorResponseErrorDetails");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
